version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  registry:
    image: ${DEPLOY_IMAGE_REGISTRY:-registry:2}
#:log |    logging: *loki-logging
#:port|    ports:
#:port|      - ${DEPLOY_PORT_REGISTORY:-5000}:5000
    networks:
      - external_network
    volumes:
      - data:/var/lib/registry
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
      labels:
        - "traefik.enable=true" #!port
        - "traefik.http.routers.registry_web.rule=Host(`docker.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.registry_web.entrypoints=webhttps"
        - "traefik.http.routers.registry_web.tls.certresolver=le"
        - "traefik.http.services.registry_web.loadbalancer.server.port=5000"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT${DEPLOY_DATA_ROOT:-/registry/var}/data"
  ssl:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT${DEPLOY_DATA_ROOT:-/registry/var}/ssl"
