version: "3.2"

services:
  registry:
    image: registry:2
    restart: always
    networks:
      - external_network
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/ssl/docker.<secret:HOST_NAME>.crt
      - REGISTRY_HTTP_TLS_KEY=/ssl/docker.<secret:HOST_NAME>.crt.key
    volumes:
      - data:/var/lib/registry
      - ssl:/ssl
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registry_web.rule=Host(`docker.<secret:HOST_NAME>`)"
        - "traefik.http.routers.registry_web.entrypoints=websecure"
        - "traefik.http.routers.registry_web.tls.certresolver=le"
        - "traefik.http.services.registry_web.loadbalancer.server.port=5000"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=nfs.<secret:HOST_NAME>,nolock,soft,rw"
      device: ":/srv/nfs/registry/data"
  ssl:
    driver_opts:
      type: "nfs"
      o: "addr=nfs.<secret:HOST_NAME>,nolock,soft,rw"
      device: ":/srv/nfs/registry/ssl"
