version: "3.2"

services:
  registry:
    image: registry:2
    networks:
      - external_network
    volumes:
      - data:/var/lib/registry
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registry_web.rule=Host(`docker.<secret:HOST_NAME>`)"
        - "traefik.http.routers.registry_web.entrypoints=webhttps"
        - "traefik.http.routers.registry_web.tls.certresolver=le"
        - "traefik.http.services.registry_web.loadbalancer.server.port=5000"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT/registry/data"
  ssl:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT/registry/ssl"
