version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  registry:
    image: ${DEPLOY_IMAGE_REGISTRY:-registry:2}
#:log |    logging: *loki-logging
#:port|    ports:
#:port|      - ${DEPLOY_PORT_REGISTORY:-5000}:5000
    networks:
      - external_network
    volumes:
      - data:/var/lib/registry
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
      labels:
        - "traefik.enable=true" #!port
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-registry}.rule=Host(`${DEPLOY_SUBDOMAIN:-docker}.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-registry}.entrypoints=webhttps"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-registry}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-registry}.loadbalancer.server.port=5000"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-registry}/data"
  ssl:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-registry}/ssl"
