version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-mtlynch/mediagoblin}
#:log |    logging: *loki-logging
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-6543}:6543
    networks:
      - external_network
    volumes:
      - data:/var/lib/mediagoblin
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!port
        - "traefik.http.routers.mediagoblin_web.rule=Host(`${DEPLOY_SUBDOMAIN:-mediagoblin}.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.mediagoblin_web.entrypoints=webhttps"
        - "traefik.http.routers.mediagoblin_web.tls.certresolver=le"
        - "traefik.http.services.mediagoblin_web.loadbalancer.server.port=6543"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT${DEPLOY_DATA_ROOT:-/mediagoblin/var}/data"
