version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: wildcat/scylla:1.1.7
#    logging: *loki-logging
    networks:
      - external_network
    volumes:
      - data:/var/www/scylla
    ports:
      - 8081:8081
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.scylla_web.rule=Host(`scylla.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.scylla_web.entrypoints=webhttps"
        - "traefik.http.routers.scylla_web.tls.certresolver=le"
        - "traefik.http.services.scylla_web.loadbalancer.server.port=8899"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT/scylla/var/data"
