version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-gotson/komga}
#:log |    logging: *loki-logging
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-8080}:8080
    networks:
      - external_network
    volumes:
      - data:/config
      - books:/books
      - sdu:/mnt/sdu
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!port
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-komga}.rule=Host(`${DEPLOY_SUBDOMAIN:-komga}.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-komga}.entrypoints=webhttps"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-komga}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-komga}.loadbalancer.server.port=8080"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-komga}/data"
  books:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_BOOK_HOST,nolock,soft,rw"
      device: ":$DEPLOY_BOOK_ROOT"
  sdu:
    driver: "sapk/plugin-rclone:latest"
    driver_opts:
      args: "--attr-timeout 60s --vfs-cache-mode full"
      config: "$DEPLOY_RCLONE_SDU_CONFIG"
      remote: "$DEPLOY_RCLONE_SDU_REMOTE"
