version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-darthsim/imgproxy:v2}
#:log |    logging: *loki-logging
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-8080}:8080
    env_file: ${DEPLOY_CONFIG_WEB:-config/config.env}
    networks:
      - external_network
#:rclone|#:media |    volumes:
#:media |    volumes: #!rclone
#:media |      - media:/media
#:rclone|    volumes: #!media
#:rclone|      - rclone:$DEPLOY_RCLONE_LOCAL
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-imgproxy}.rule=Host(`${DEPLOY_SUBDOMAIN:-imgproxy}.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-imgproxy}.entrypoints=webhttps"
#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-imgproxy}.tls.options=sslVerifyClient@file"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-imgproxy}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-imgproxy}.loadbalancer.server.port=8080"

networks:
  external_network:
    external: true

#:rclone|#:media |volumes:
#:media |volumes: #!rclone
#:rclone|volumes: #!media
#:media |  media:
#:media |    driver_opts:
#:media |      type: "nfs"
#:media |      o: "addr=$DEPLOY_MEDIA_HOST,nolock,soft,rw"
#:media |      device: ":$DEPLOY_MEDIA_ROOT"
#:rclone|  rclone:
#:rclone|    driver: "sapk/plugin-rclone:latest"
#:rclone|    driver_opts:
#:rclone|      args: "--allow-root --allow-other --attr-timeout 60s --vfs-cache-mode full"
#:rclone|      config: "$DEPLOY_RCLONE_CONFIG"
#:rclone|      remote: "$DEPLOY_RCLONE_REMOTE"
