version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  db:
    image: mysql/mysql-server:8.0
#    logging: *loki-logging
    env_file:
      - config/docker.env
    networks:
      - internal_network
    volumes:
      - db:/var/lib/mysql
      - sql:/docker-entrypoint-initdb.d/
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_DB:-node.labels.ignore != true}

  web:
    image: mylist
#    logging: *loki-logging
    networks:
      - external_network
      - internal_network
    env_file:
      - config/docker.env
    volumes:
      - jar:/opt/mylist/jar
      - static:/opt/mylist/static
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mylist_web.rule=Host(`list.<secret:HOST_NAME>`)"
        - "traefik.http.routers.mylist_web.entrypoints=webhttps"
        - "traefik.http.routers.mylist_web.tls.certresolver=le"
        - "traefik.http.services.mylist_web.loadbalancer.server.port=8080"

networks:
  external_network:
    external: true
  internal_network:
    internal: true

volumes:
  db:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT/mylist/db"
  sql:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT/mylist/sql"
  jar:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT/mylist/jar"
  static:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT/mylist/static"
