version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-mylist}
#:log |    logging: *loki-logging
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-8080}:8080
    networks:
      - external_network
      - internal_network
    env_file:
      - config/docker.env
    volumes:
      - jar:/opt/mylist/jar
      - static:/opt/mylist/static
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!port
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-mylist}.rule=Host(`${DEPLOY_SUBDOMAIN:-list}.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-mylist}.entrypoints=webhttps"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-mylist}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-mylist}.loadbalancer.server.port=8080"

  db:
    image: ${DEPLOY_IMAGE_DB:-mysql/mysql-server:8.0}
#:log |    logging: *loki-logging
    env_file:
      - config/docker.env
    networks:
      - internal_network
    volumes:
      - db:/var/lib/mysql
    configs:
      - source: initdb-config
        target: /docker-entrypoint-initdb.d/mysql.sql
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_DB:-node.labels.ignore != true}

networks:
  external_network:
    external: true
  internal_network:
    internal: true

configs:
  initdb-config:
    file: ./config/mysql.sql

volumes:
  db:
    driver_opts:
      type: "nfs"
      o: "addr=$$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$$DEPLOY_NFS_ROOT/${DEPLOY_STACK_NAME:-mylist}/db"
  jar:
    driver_opts:
      type: "nfs"
      o: "addr=$$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$$DEPLOY_NFS_ROOT/${DEPLOY_STACK_NAME:-mylist}/jar"
  static:
    driver_opts:
      type: "nfs"
      o: "addr=$$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$$DEPLOY_NFS_ROOT/${DEPLOY_STACK_NAME:-mylist}/static"
