version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-mylnmp:latest}
#:log |    logging: *loki-logging
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB_HTTP:-80}:80
    environment:
      - DB_HOST=$DEPLOY_DB_HOST
      - DB_PORT=$DEPLOY_DB_PORT
      - DB_LOCAL_PORT=$DEPLOY_DB_LOCAL_PORT
      - DEBUG=$DEPLOY_DEBUG
    networks:
      - external_network
    volumes:
      - www:/var/www
#:media |      - media:/media
#:rclone|      - rclone:$DEPLOY_RCLONE_LOCAL
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!port
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-lnmp}.rule=Host(`${DEPLOY_SUBDOMAIN:-lnmp}.${DEPLOY_HOSTNAME}`)" #!custom_router_rule
#:custom_router_rule|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-lnmp}.rule=$DEPLOY_CUSTOM_ROUTER_RULE"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-lnmp}.entrypoints=webhttps" #!client_ssl
#:client_ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-archivebox}.tls.options=sslVerifyClient@file"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-lnmp}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-lnmp}.loadbalancer.server.port=80"

networks:
  external_network:
    external: true

volumes:
  www:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-lnmp}/www"
#:media |  media:
#:media |    driver_opts:
#:media |      type: "nfs"
#:media |      o: "addr=$DEPLOY_MEDIA_HOST,nolock,soft,rw"
#:media |      device: ":$DEPLOY_MEDIA_ROOT"
#:rclone|  rclone:
#:rclone|    driver: "sapk/plugin-rclone:latest"
#:rclone|    driver_opts:
#:rclone|      args: "--allow-root --allow-other --attr-timeout 60s --vfs-cache-mode full"
#:rclone|      config: "$DEPLOY_RCLONE_CONFIG"
#:rclone|      remote: "$DEPLOY_RCLONE_REMOTE"
