version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-linuxserver/calibre-web:0.6.8-ls78}
#:log |    logging: *loki-logging
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-8083}:8083
    networks:
      - external_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - data:/config
      - books:/books
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!port
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-calibre}.rule=Host(`${DEPLOY_SUBDOMAIN:-book}.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-calibre}.entrypoints=webhttps"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-calibre}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-calibre}.loadbalancer.server.port=8083"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-calibre}/data"
  books:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_EBOOK_HOST,nolock,soft,rw"
      device: ":$DEPLOY_EBOOK_ROOT"
