version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: hkalexling/mango:v0.12.2
#    logging: *loki-logging
    networks:
      - external_network
    volumes:
      - config:/root/.config/mango
      - data:/root/mango
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mango_web.rule=Host(`mango.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.mango_web.entrypoints=webhttps"
        - "traefik.http.routers.mango_web.tls.certresolver=le"
        - "traefik.http.services.mango_web.loadbalancer.server.port=9000"

networks:
  external_network:
    external: true

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT/mango/var/config"
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT/mango/var/data"
