version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: hkalexling/mango:v0.12.2
#:log |    logging: *loki-logging
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-9000}:9000
    networks:
      - external_network
    volumes:
      - data:/root/mango
    configs:
      - source: mango-config
        target: /root/.config/mango/config.yml
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!port
        - "traefik.http.routers.mango_web.rule=Host(`mango.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.mango_web.entrypoints=webhttps"
        - "traefik.http.routers.mango_web.tls.certresolver=le"
        - "traefik.http.services.mango_web.loadbalancer.server.port=9000"

networks:
  external_network:
    external: true

configs:
  mango-config:
    file: ./config/config.yml

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT${DEPLOY_DATA_ROOT:-/mango/var}/config"
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT${DEPLOY_DATA_ROOT:-/mango/var}/data"
