---
port: 9000
base_url: /
session_secret: mango-session-secret
library_path: /root/mango/library
db_path: /root/mango/mango.db
scan_interval_minutes: 5
log_level: info
upload_path: /root/mango/uploads
plugin_path: /root/mango/plugins
mangadex:
  base_url: https://mangadex.org
  api_url: https://mangadex.org/api
  download_wait_seconds: 5
  download_retries: 4
  download_queue_db_path: /root/mango/queue.db
  chapter_rename_rule: '[Vol.{volume} ][Ch.{chapter} ]{title|id}'
  manga_rename_rule: '{title}'
