version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: setzero/oneindex
#    logging: *loki-logging
    environment:
      REFRESH_TOKEN: '0 * * * *'
      REFRESH_CACHE: '*/10 * * * *'
    networks:
      - external_network
    volumes:
      - data:/var/www/html/config
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.oneindex_web.rule=Host(`one.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.oneindex_web.entrypoints=webhttps"
        - "traefik.http.routers.oneindex_web.tls.certresolver=le"
        - "traefik.http.services.oneindex_web.loadbalancer.server.port=80"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT${DEPLOY_DATA_ROOT:-/oneindex/var}/data"
