version: "3.2"

services:
  web:
    image: setzero/oneindex
    environment:
      REFRESH_TOKEN: '0 * * * *'
      REFRESH_CACHE: '*/10 * * * *'
    networks:
      - external_network
    volumes:
      - data:/var/www/html/config
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.oneindex_web.rule=Host(`one.<secret:HOST_NAME>`)"
        - "traefik.http.routers.oneindex_web.entrypoints=webhttps"
        - "traefik.http.routers.oneindex_web.tls.certresolver=le"
        - "traefik.http.services.oneindex_web.loadbalancer.server.port=80"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_NFS_HOST,nolock,soft,rw"
      device: ":$DEPLOY_NFS_ROOT/oneindex/data"
